# Generated by Django 5.0.6 on 2024-06-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_be', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='data',
        ),
        migrations.AddField(
            model_name='saldo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='controle_gastos_be.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
